{{- if and .Values.database.enabled .Values.postgresql.enabled (not .Values.database.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quiz-a-roo.fullname" . }}-postgres
  labels:
    {{- include "quiz-a-roo.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: "postgres://{{ .Values.postgresql.auth.username | urlquery }}:{{ .Values.postgresql.auth.password | urlquery }}@{{ include "quiz-a-roo.fullname" . }}-postgres:5432/{{ .Values.postgresql.auth.database | urlquery }}"
  POSTGRES_USER: {{ .Values.postgresql.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
  POSTGRES_DB: {{ .Values.postgresql.auth.database | quote }}
{{- end }}
