{{- if and .Values.database.enabled .Values.postgresql.enabled (not .Values.database.existingSecret) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "quiz-a-roo.fullname" . }}-postgres
  labels:
    {{- include "quiz-a-roo.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP
  selector:
    {{- include "quiz-a-roo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
{{- end }}
